#!/usr/bin/env ruby

$user    = ENV['USER']

def get_acl_access_data
  # read in ACL data
  acl_file = File.read('.git/acl').split("\n").reject { |line| line == '' || line[0] == '#' }
  access = {}
  acl_file.each do |line|
    avail, users, path = line.split('|')
    next unless avail == 'avail'
    users.split(',').each do |user|
      access[user] ||= []
      access[user] << path
    end
  end
  access
end

# only allows certain users to modify certain subdirectories in a project
def check_directory_perms
  access = get_acl_access_data
  
  files_modified = `git diff-index --cached --name-only HEAD`
  files_modified.select do |path|
    has_file_access = false
    next if path.size == 0
    access[$user].each do |access_path|
      has_file_access = true if !access_path || path.include?(access_path)
    end
    if !has_file_access
      puts "[POLICY] You do not have access to push to #{path}"
      exit 1
    end
  end
end

check_directory_perms

